# chapter 1
# see <https://quarto.org/docs/books/> for book setup and options

project:
  type: book
  output-dir: _output
format:
  pdf:
    # pdf options: <https://quarto.org/docs/reference/formats/pdf.html#references>
    # toc: true
    number-sections: true
    # colorlinks: true
    citeproc: true
    bibliography: ['wine/wine.bib',]

execute:
  daemon: true
book:
  title: 'Chapter One: Wine Signal Acquisition'
  author: Jonathan Stathakis
  date: '2024-06-19 12:44:07'
  # page-navigation: true
  # dont need '-' for chapter keyword, do for 'part'. alternate chapters and parts to define structure. Note: cannot add another part below the nested chapter.
  chapters:
    - index.qmd
    - part: introduction.qmd
      chapters:
        - wine/wine.qmd
        - the_data/the_data.qmd
    - references.qmd
    