# see https://quarto.org/docs/reference/projects/options.html
project:
  output-dir: _output
  execute-dir: project
format:
  # see https://quarto.org/docs/output-formats/html-basics.html
  html:
    embed-resources: true  
execute:
  daemon: true  
