"""

"""
import sys
from wine_analysis_hplc_uv.chemstation.chemstation_to_db_methods import (
    chromatogram_spectra_to_db,
)

sys.path.append("/Users/jonathan/mres_thesis/wine_analysis_hplc_uv/tests")
from mytestmethods.mytestmethods import test_report
from wine_analysis_hplc_uv.chemstation import uv_extractor
from wine_analysis_hplc_uv.df_methods import df_methods
from chemstation_tests import (
    chemstation_logger,
    test_logger,
)
import os
import shutil
import pandas as pd
import duckdb as db
import rainbow as rb


def test_uv_data_to_df():
    tests = []
    test_report(tests)


def get_file_path():
    return "/Users/jonathan/mres_thesis/wine_analysis_hplc_uv/tests/test_data/125.D/DAD1.UV"


def test_melt():
    """
    2023-06-11 19:21:44 test integration of melt.
    """
    filepath = get_file_path()

    df = uv_extractor.uv_data_to_df(filepath)
    col_list = df.columns.tolist()
    # assert col_list = [''] # check that the columns are assigned as expected
    # assert len(col_list) ==
    assert df.isna().sum().sum() == 0  # ensure no NA's generated by melt.


def main():
    test_uv_data_to_df()
    return None


if __name__ == "__main__":
    main()
