---
title: "The Data"
---

# Dev Outline

TODO
1. [ ] fingerprinting
    1. [ ] what is fingerprinting
    2. [ ] applications of fingerprinting
    3. [ ] why fingerprinting was selected
2. [ ] acquisition
    1. common methods of data acquisition in fingerprinting
    1. [ ] find common methods, list them out, describe.
    2. rp-hplc-dad
        1. [ ] rp-hplc
        1. [ ] hplc
            1. [ ] chromatography
            2. [ ] high pressure liquid chromatography
            3. [ ] applications of hplc
        2. [ ] rp
            1. [ ] what is rp
            2. [ ] applications of rp
        3. [ ] examples of use of rp-hplc in wine
        2. [ ] dad
        3. [ ] what is hplc-dad
        4. [ ] what are common applications of hplc-dad
        5. [ ] why was hplc-dad selected
2. [ ] hplc-dad signal enhancement through PCD
    1. what is pcd
    2. [ ] why is PCD
    3. [ ] applications of hplc-pcd
    4. common derivative agents
    5. Describe each.
    5. [ ] CUPRAC
    1. [ ] what is CUPRAC
    2. [ ] Why is cuprac
    3. [ ] applications of cuprac
    4. [ ] examples of hplc-cuprac
3. [ ] Expected Visible Analytes in Wine Chromatograms under Each detection method
    1. [ ] raw
    2. [ ] cuprac
4. [ ] variance observation through clustering
    1. [ ] what is sample variance
    2. [ ] PCA
    1. [ ] what is PCA
        1. PCA clustering
        2. [ ] how does it work
        3. [ ] how can it be used
        4. [ ] examples of its use